<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SysIn.Core\SysIn.Core.csproj" />
    <ProjectReference Include="..\SysIn.Telemetry\SysIn.Telemetry.csproj" />
    <ProjectReference Include="..\SysIn.Providers\SysIn.Providers.csproj" />
    <PackageReference Include="System.Management" />
  </ItemGroup>
</Project>
